# Generated by Django 4.2.3 on 2023-08-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='признак подписки'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='version',
            field=models.CharField(default=1, max_length=50, verbose_name='версия подписки'),
        ),
    ]
